import 'phrase.dart';

List<Phrase> getInitialPhrases() {
  return [
    Phrase(ru: "Дайте нам знать, если что-то изменится", en: "Let us know if anything changes"),
    Phrase(ru: "Жду вашего ответа", en: "I look forward to hearing from you"),
    Phrase(ru: "Мы ценим сотрудничество", en: "We appreciate your cooperation"),
    Phrase(ru: "Свяжитесь при возможности", en: "Contact me at your convenience"),
    Phrase(ru: "Я скоро отвечу вам", en: "I will get back to you soon"),
    Phrase(ru: "Давайте подведем итоги", en: "Let's wrap this up"),
    Phrase(ru: "Мы на одной волне", en: "We are on the same page"),
    Phrase(ru: "Это беспроигрышный вариант", en: "It is a win-win situation"),
    Phrase(ru: "Можете пояснить это?", en: "Could you clarify that?"),
    Phrase(ru: "В долгосрочной перспективе", en: "In the long run"),
    Phrase(ru: "Прийти к соглашению", en: "Reach an agreement"),
    Phrase(ru: "Принять решение", en: "Make a decision"),
    Phrase(ru: "Внести вклад", en: "Make a contribution"),
    Phrase(ru: "Уложиться в дедлайн", en: "Meet a deadline"),
    Phrase(ru: "Провести встречу", en: "Hold a meeting"),
    Phrase(ru: "Обратить внимание на детали", en: "Pay attention to details"),
    Phrase(ru: "Это не входит в мои обязанности", en: "This is outside my responsibilities"),
    Phrase(ru: "Давайте перейдем к делу", en: "Let's get down to business"),
    Phrase(ru: "Вкратце", en: "In a nutshell"),
    Phrase(ru: "Сдвинуть с мертвой точки", en: "Get the ball rolling"),
    Phrase(ru: "Я полностью согласен", en: "I couldn't agree more"),
    Phrase(ru: "У меня другое мнение", en: "I have a different opinion"),
    Phrase(ru: "Давайте обсудим это позже", en: "Let's discuss it later"),
    Phrase(ru: "Это главный приоритет", en: "This is a top priority"),
    Phrase(ru: "Мы немного отклонились от темы", en: "We are getting a bit off track"),
    Phrase(ru: "Вернемся к обсуждению", en: "Let's get back to the point"),
    Phrase(ru: "Я подготовлю отчет", en: "I will prepare a report"),
    Phrase(ru: "Нам нужно сократить расходы", en: "We need to cut costs"),
    Phrase(ru: "Это стоит обдумать", en: "It is worth considering"),
    Phrase(ru: "Я уточню это", en: "I will look into that"),
    Phrase(ru: "Это зависит от ситуации", en: "It depends on the situation"),
    Phrase(ru: "Насколько я знаю", en: "As far as I know"),
    Phrase(ru: "Честно говоря", en: "To be honest"),
    Phrase(ru: "С моей точки зрения", en: "From my point of view"),
    Phrase(ru: "Я ценю вашу помощь", en: "I appreciate your help"),
    Phrase(ru: "Давайте назначим встречу", en: "Let's schedule a meeting"),
    Phrase(ru: "Я перезвоню вам", en: "I will call you back"),
    Phrase(ru: "Приятно познакомиться", en: "It is a pleasure to meet you"),
    Phrase(ru: "Как дела в бизнесе?", en: "How is business going?"),
    Phrase(ru: "Мы должны сосредоточиться на", en: "We should focus on"),
    Phrase(ru: "Это сложный вопрос", en: "This is a tough question"),
    Phrase(ru: "Я не совсем понимаю", en: "I don't quite understand"),
    Phrase(ru: "Не могли бы вы повторить?", en: "Could you please repeat that?"),
    Phrase(ru: "Спасибо за ваше время", en: "Thank you for your time"),
    Phrase(ru: "Все под контролем", en: "Everything is under control"),
    Phrase(ru: "Мы должны действовать быстро", en: "We must act quickly"),
    Phrase(ru: "Это отличная возможность", en: "This is a great opportunity"),
    Phrase(ru: "Я открыт для предложений", en: "I am open to suggestions"),
    Phrase(ru: "Давайте взвесим все за и против", en: "Let's weigh the pros and cons"),
    Phrase(ru: "Это может сработать", en: "This might work"),
    Phrase(ru: "Я сомневаюсь в этом", en: "I doubt that"),
    Phrase(ru: "Нам нужно больше данных", en: "We need more data"),
    Phrase(ru: "Результаты впечатляют", en: "The results are impressive"),
    Phrase(ru: "Это пустая трата времени", en: "It is a waste of time"),
    Phrase(ru: "Я беру ответственность", en: "I take responsibility"),
    Phrase(ru: "Проект идет по плану", en: "The project is on track"),
    Phrase(ru: "У нас возникла проблема", en: "We have run into a problem"),
    Phrase(ru: "Как продвигается проект?", en: "How is the project coming along?"),
    Phrase(ru: "Это выходит за рамки бюджета", en: "It is over budget"),
    Phrase(ru: "Нам нужно найти решение", en: "We need to find a solution"),
    Phrase(ru: "Это имеет смысл", en: "That makes sense"),
    Phrase(ru: "Я бы хотел добавить", en: "I would like to add"),
    Phrase(ru: "Позвольте мне объяснить", en: "Let me explain"),
    Phrase(ru: "В конечном итоге", en: "At the end of the day"),
    Phrase(ru: "Держать в курсе", en: "Keep someone in the loop"),
    Phrase(ru: "Справиться с задачей", en: "Manage a task"),
    Phrase(ru: "Расставить приоритеты", en: "Set priorities"),
    Phrase(ru: "Общая картина", en: "The big picture"),
    Phrase(ru: "Достичь цели", en: "Achieve a goal"),
    Phrase(ru: "Провести исследование", en: "Carry out research"),
    Phrase(ru: "Принять вызов", en: "Take on a challenge"),
    Phrase(ru: "Повысить эффективность", en: "Improve efficiency"),
    Phrase(ru: "Расширить рынок", en: "Expand the market"),
    Phrase(ru: "Привлечь клиентов", en: "Attract customers"),
    Phrase(ru: "Запустить продукт", en: "Launch a product"),
    Phrase(ru: "Предварительный план", en: "A tentative plan"),
    Phrase(ru: "Разногласия", en: "A point of disagreement"),
    Phrase(ru: "Конкурентное преимущество", en: "Competitive advantage"),
    Phrase(ru: "Корпоративная культура", en: "Corporate culture"),
    Phrase(ru: "Основная компетенция", en: "Core competency"),
    Phrase(ru: "Денежный поток", en: "Cash flow"),
    Phrase(ru: "Целевая аудитория", en: "Target audience"),
    Phrase(ru: "Обратная связь", en: "Feedback"),
    Phrase(ru: "Прийти к компромиссу", en: "Reach a compromise"),
    Phrase(ru: "Сорвать сделку", en: "Break a deal"),
    Phrase(ru: "Заключить контракт", en: "Sign a contract"),
    Phrase(ru: "Вести переговоры", en: "Conduct negotiations"),
    Phrase(ru: "Поддерживать отношения", en: "Maintain relations"),
    Phrase(ru: "Подвести черту", en: "Draw the line"),
    Phrase(ru: "Поделиться мыслями", en: "Share thoughts"),
    Phrase(ru: "Взять на себя инициативу", en: "Take the initiative"),
    Phrase(ru: "Оправдать ожидания", en: "Meet expectations"),
    Phrase(ru: "Служебная записка", en: "Internal memo"),
    Phrase(ru: "Повестка дня", en: "The agenda"),
    Phrase(ru: "Протокол встречи", en: "Minutes of the meeting"),
    Phrase(ru: "Кадровые перестановки", en: "Staff turnover"),
    Phrase(ru: "Совет директоров", en: "Board of directors"),
    Phrase(ru: "Годовой отчет", en: "Annual report"),
    Phrase(ru: "Филиал компании", en: "Branch of the company"),
    Phrase(ru: "Штаб-квартира", en: "Headquarters"),
  ];
}